namespace Chess1
{
    /// <summary>
    /// Main Class of the Chess program (generated by Visual Studio)
    /// </summary>
    internal static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Application.Run(new ChessboardForm());
        }
    }
}